ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0
    sensor_timeout: 0.8
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    odom0: /diff_drive_controller/odom
    odom0_config: [false,  false,  false,
                   false, false, false, # Odom의 yaw 각도는 사용하지 않음
                   true,  false, false,
                   false, false, true,
                   false, false, false]
                   
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, false, # Yaw (절대 방향 값 사용 안 함)
                  false, false, false,
                  false, false, true,  # VYaw (자이로스코프: 회전 각속도 사용)
                  false,  false,  false] # 선형 가속도
    
    imu0_relative: true