laser_filter:
  ros__parameters:
    use_sim_time: false
    filter1:
      name: range
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.33
        upper_threshold: 10.0
        lower_replacement_value: .NaN
        upper_replacement_value: .NaN
