slam_toolbox:
  ros__parameters:

    use_sim_time: false

    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    scan_queue_size: 1

    min_laser_range: 0.3
    max_laser_range: 10.0

    minimum_travel_distance: 0.01
    minimum_travel_heading: 0.01
    map_update_interval: 0.5

    # timestamp mismatch가 계속 남으면 진단용으로만 고려
    # restamp_tf: true