slam_toolbox:
  ros__parameters:

    #시간동기 해결
    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    scan_queue_size: 20

    #setting
    use_sim_time: false

    #safety
    minimum_travel_distance: 0.01
    minimum_travel_heading: 0.01
    map_update_interval: 0.5

